export enum UserRole {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  DIRECTOR = 'DIRECTOR',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  STATION_MANAGER = 'STATION_MANAGER',
  ATTENDANT = 'ATTENDANT',
  STOREKEEPER = 'STOREKEEPER',
  SAFETY_OFFICER = 'SAFETY_OFFICER',
  AUDITOR = 'AUDITOR',
}

export enum StationStatus {
  ACTIVE = 'ACTIVE',
  TEMPORARILY_CLOSED = 'TEMPORARILY_CLOSED',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
}

export enum StockMovementType {
  OPENING_STOCK = 'OPENING_STOCK',
  SUPPLIER_DELIVERY = 'SUPPLIER_DELIVERY',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  REFILL_SALE = 'REFILL_SALE',
  INTERNAL_CONSUMPTION = 'INTERNAL_CONSUMPTION',
  LEAKAGE_LOSS = 'LEAKAGE_LOSS',
  TESTING_CALIBRATION = 'TESTING_CALIBRATION',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  CLOSING_STOCK = 'CLOSING_STOCK',
}

export enum DeliveryStatus {
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  SUPPLIER_DISPATCH = 'SUPPLIER_DISPATCH',
  STATION_RECEIPT = 'STATION_RECEIPT',
  QUANTITY_VERIFICATION = 'QUANTITY_VERIFICATION',
  MANAGER_APPROVAL = 'MANAGER_APPROVAL',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',
  ACCOUNTS_PAYABLE = 'ACCOUNTS_PAYABLE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  AIRTEL_MONEY = 'AIRTEL_MONEY',
  TNM_MPAMBA = 'TNM_MPAMBA',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CARD = 'CARD',
  CUSTOMER_ACCOUNT = 'CUSTOMER_ACCOUNT',
  MIXED = 'MIXED',
}

export enum SaleStatus {
  COMPLETED = 'COMPLETED',
  VOIDED = 'VOIDED',
  REFUNDED = 'REFUNDED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum CylinderOwnership {
  COMPANY = 'COMPANY',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
  DEPOSIT = 'DEPOSIT',
}

export enum CylinderStatus {
  AVAILABLE = 'AVAILABLE',
  FILLED = 'FILLED',
  EMPTY = 'EMPTY',
  WITH_CUSTOMER = 'WITH_CUSTOMER',
  IN_TRANSIT = 'IN_TRANSIT',
  UNDER_INSPECTION = 'UNDER_INSPECTION',
  DAMAGED = 'DAMAGED',
  CONDEMNED = 'CONDEMNED',
  LOST = 'LOST',
}

export enum TransferStatus {
  REQUESTED = 'REQUESTED',
  SOURCE_APPROVED = 'SOURCE_APPROVED',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED = 'RECEIVED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum TransferItemType {
  LPG = 'LPG',
  CYLINDER = 'CYLINDER',
  ACCESSORY = 'ACCESSORY',
}

export enum ShiftStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum ExpenseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CustomerType {
  HOUSEHOLD = 'HOUSEHOLD',
  COMMERCIAL = 'COMMERCIAL',
  INSTITUTIONAL = 'INSTITUTIONAL',
  AGENT = 'AGENT',
}

export enum ProductCategory {
  LPG_REFILL = 'LPG_REFILL',
  FILLED_CYLINDER = 'FILLED_CYLINDER',
  EMPTY_CYLINDER = 'EMPTY_CYLINDER',
  DEPOSIT = 'DEPOSIT',
  ACCESSORY = 'ACCESSORY',
}
