export enum UserRole {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  DIRECTOR = 'DIRECTOR',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  STATION_MANAGER = 'STATION_MANAGER',
  ATTENDANT = 'ATTENDANT',
  STOREKEEPER = 'STOREKEEPER',
  SAFETY_OFFICER = 'SAFETY_OFFICER',
  AUDITOR = 'AUDITOR',
}

export enum StationStatus {
  ACTIVE = 'ACTIVE',
  TEMPORARILY_CLOSED = 'TEMPORARILY_CLOSED',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
}

export enum StockMovementType {
  OPENING_STOCK = 'OPENING_STOCK',
  SUPPLIER_DELIVERY = 'SUPPLIER_DELIVERY',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  REFILL_SALE = 'REFILL_SALE',
  INTERNAL_CONSUMPTION = 'INTERNAL_CONSUMPTION',
  LEAKAGE_LOSS = 'LEAKAGE_LOSS',
  TESTING_CALIBRATION = 'TESTING_CALIBRATION',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  CLOSING_STOCK = 'CLOSING_STOCK',
}

export enum DeliveryStatus {
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  SUPPLIER_DISPATCH = 'SUPPLIER_DISPATCH',
  STATION_RECEIPT = 'STATION_RECEIPT',
  QUANTITY_VERIFICATION = 'QUANTITY_VERIFICATION',
  MANAGER_APPROVAL = 'MANAGER_APPROVAL',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',
  ACCOUNTS_PAYABLE = 'ACCOUNTS_PAYABLE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  AIRTEL_MONEY = 'AIRTEL_MONEY',
  TNM_MPAMBA = 'TNM_MPAMBA',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CARD = 'CARD',
  CUSTOMER_ACCOUNT = 'CUSTOMER_ACCOUNT',
  MIXED = 'MIXED',
}

export enum SaleStatus {
  COMPLETED = 'COMPLETED',
  VOIDED = 'VOIDED',
  REFUNDED = 'REFUNDED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum CylinderOwnership {
  COMPANY = 'COMPANY',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
  DEPOSIT = 'DEPOSIT',
}

export enum CylinderStatus {
  AVAILABLE = 'AVAILABLE',
  FILLED = 'FILLED',
  EMPTY = 'EMPTY',
  WITH_CUSTOMER = 'WITH_CUSTOMER',
  IN_TRANSIT = 'IN_TRANSIT',
  UNDER_INSPECTION = 'UNDER_INSPECTION',
  DAMAGED = 'DAMAGED',
  CONDEMNED = 'CONDEMNED',
  LOST = 'LOST',
}

export enum TransferStatus {
  REQUESTED = 'REQUESTED',
  SOURCE_APPROVED = 'SOURCE_APPROVED',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED = 'RECEIVED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum TransferItemType {
  LPG = 'LPG',
  CYLINDER = 'CYLINDER',
  ACCESSORY = 'ACCESSORY',
}

export enum ShiftStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum ExpenseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CustomerType {
  HOUSEHOLD = 'HOUSEHOLD',
  COMMERCIAL = 'COMMERCIAL',
  INSTITUTIONAL = 'INSTITUTIONAL',
  AGENT = 'AGENT',
}

export enum ProductCategory {
  LPG_REFILL = 'LPG_REFILL',
  FILLED_CYLINDER = 'FILLED_CYLINDER',
  EMPTY_CYLINDER = 'EMPTY_CYLINDER',
  DEPOSIT = 'DEPOSIT',
  ACCESSORY = 'ACCESSORY',
  BUNDLE = 'BUNDLE',
}

/** Haroti Gas commercial revenue streams (Project Charter §1). */
export enum CommercialStream {
  BULK_WHOLESALE = 'BULK_WHOLESALE',
  RETAIL_FORECOURT = 'RETAIL_FORECOURT',
  FRANCHISE = 'FRANCHISE',
  PAYC = 'PAYC',
  ACCESSORIES = 'ACCESSORIES',
}

export enum WarehouseType {
  CENTRAL_DEPOT = 'CENTRAL_DEPOT',
  OWNED_STATION = 'OWNED_STATION',
  FRANCHISE_OUTLET = 'FRANCHISE_OUTLET',
  AGENT_POOL = 'AGENT_POOL',
}

/** Tiered price engine channels (Charter §10.3). */
export enum SalesChannel {
  RETAIL_LIST = 'RETAIL_LIST',
  WHOLESALE = 'WHOLESALE',
  FRANCHISE_PURCHASE = 'FRANCHISE_PURCHASE',
  AGENT_COMMISSION = 'AGENT_COMMISSION',
}

export enum StockOwnership {
  OWNED = 'OWNED',
  CONSIGNMENT = 'CONSIGNMENT',
}

export enum Currency {
  MWK = 'MWK',
  USD = 'USD',
}

export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  ORDERED = 'ORDERED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}

/** Station requisition: request → GM approve → finance pay. */
export enum RequisitionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  GM_APPROVED = 'GM_APPROVED',
  READY_TO_PAY = 'READY_TO_PAY',
  PAID = 'PAID',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

/** ERP accounting matrix events (Charter §4). */
export enum JournalEventType {
  ACCESSORY_GRN = 'ACCESSORY_GRN',
  ACCESSORY_TRANSFER = 'ACCESSORY_TRANSFER',
  ACCESSORY_CONSIGNMENT = 'ACCESSORY_CONSIGNMENT',
  ACCESSORY_RETAIL_SALE = 'ACCESSORY_RETAIL_SALE',
  ACCESSORY_COGS = 'ACCESSORY_COGS',
  FRANCHISE_SETTLEMENT = 'FRANCHISE_SETTLEMENT',
  BUNDLE_SALE = 'BUNDLE_SALE',
  LPG_DELIVERY = 'LPG_DELIVERY',
  LPG_REFILL_SALE = 'LPG_REFILL_SALE',
  LPG_COGS = 'LPG_COGS',
  PAYC_BURN_REVENUE = 'PAYC_BURN_REVENUE',
  PAYC_CREDIT_TOPUP = 'PAYC_CREDIT_TOPUP',
  CAPITAL_EXPENDITURE = 'CAPITAL_EXPENDITURE',
  AGENT_COMMISSION = 'AGENT_COMMISSION',
  STATION_EXPENSE = 'STATION_EXPENSE',
  REQUISITION_PAYMENT = 'REQUISITION_PAYMENT',
  CUSTOMER_CREDIT_SALE = 'CUSTOMER_CREDIT_SALE',
  CUSTOMER_PAYMENT = 'CUSTOMER_PAYMENT',
}

export enum TankReadingContext {
  SHIFT_OPEN = 'SHIFT_OPEN',
  SHIFT_CLOSE = 'SHIFT_CLOSE',
  DELIVERY = 'DELIVERY',
  TRANSFER = 'TRANSFER',
  MANUAL = 'MANUAL',
}

export enum LossCaseStatus {
  OPEN = 'OPEN',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CylinderMovementType {
  ISSUE = 'ISSUE',
  RETURN = 'RETURN',
  SWAP_IN = 'SWAP_IN',
  SWAP_OUT = 'SWAP_OUT',
  TRANSFER = 'TRANSFER',
  SALE_ATTACH = 'SALE_ATTACH',
}

export enum SettlementMatchStatus {
  UNMATCHED = 'UNMATCHED',
  MATCHED = 'MATCHED',
  DISPUTED = 'DISPUTED',
}

export enum PaycMeterStatus {
  ACTIVE = 'ACTIVE',
  LOW_CREDIT = 'LOW_CREDIT',
  VALVE_CLOSED = 'VALVE_CLOSED',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum WorkOrderStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_PARTS = 'AWAITING_PARTS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum WorkOrderType {
  CYLINDER_HYDRO_TEST = 'CYLINDER_HYDRO_TEST',
  PAYC_METER_SERVICE = 'PAYC_METER_SERVICE',
  STATION_EQUIPMENT = 'STATION_EQUIPMENT',
  VEHICLE_FLEET = 'VEHICLE_FLEET',
}

export enum AssetCategory {
  STATION_EQUIPMENT = 'STATION_EQUIPMENT',
  PAYC_METER_UNIT = 'PAYC_METER_UNIT',
  VEHICLE = 'VEHICLE',
  CYLINDER = 'CYLINDER',
  IT_EQUIPMENT = 'IT_EQUIPMENT',
}

export enum AssetStatus {
  ACTIVE = 'ACTIVE',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum PaycCreditTxnType {
  TOPUP = 'TOPUP',
  BURN = 'BURN',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ProjectType {
  CAPEX_STATION = 'CAPEX_STATION',
  CAPEX_DEPOT = 'CAPEX_DEPOT',
  GRANT_FUNDED = 'GRANT_FUNDED',
  PAYC_ROLLOUT = 'PAYC_ROLLOUT',
}

export enum SettlementStatus {
  DRAFT = 'DRAFT',
  PENDING_INVOICE = 'PENDING_INVOICE',
  INVOICED = 'INVOICED',
  PAID = 'PAID',
}

export enum CommissionStatus {
  ACCRUED = 'ACCRUED',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
}
